import Head from 'next/head';
interface Types{
    page: string;
}
export default function meta({page}: Types): JSX.Element{
    return(
        <>
            <Head>
                <title>Kid. Studio | {page}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preload" href="/fonts/andalemo.ttf" as="font" crossOrigin="" />
            </Head>
        </>
    );
}