import Head from 'next/head';
import styles from "../styles/scss/workPage/_reel.module.scss";

export default function reel():JSX.Element{
    return(
        <>
            <Head>
                <title>Kid. Studio | Reel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Yooo</h1>
        </>
    )
}