import Head from 'next/head';
import styles from '../styles/scss/homePage/_home.module.scss';
import Layout from '../components/layout';
import Navigation from '../components/common/header/navigation';
import Footer from '../components/common/footer';
import Carousel from '../components/homeContent/carousel'

export default function home():JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>
          <Carousel />
        </Layout>
    </>
  )
}