import Head from 'next/head';
import Layout from '../components/layout';
import ProjectList from '../components/workContent/projectList';

export default function work():JSX.Element{
     return(
         <>
            <Head>
                <title>Kid. Studio | info</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <ProjectList />
            </Layout>
         </>
     )
}