import Head from 'next/head';
import styles from "../styles/scss/workPage/_work.module.scss";

export default function work():JSX.Element{
     return(
         <>
            <Head>
                <title>Kid. Studio | info</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
         </>
     )
}